export const GeneralConstants = {
  youFeel: 'How you feel today?',
  tested: 'How you been tested?',
  well: 'WELL',
  bad: 'BAD',
  testResults: 'TEST RESULTS',
  scanQr: 'SCAN QR',
  keepFriends:
    'Keep your friends and family safe. Scan the places where you´re to provide control of Covid-19 cases.',
  testResultsTitle: 'Test Result',
  save: 'SAVE',
  scanqr: 'My Places',
  QRtitle: 'Scan the QR code',
  date: 'Date',
  datedate:'10/03/2021',
  dateoftest:'Date of test',
  dateofrestdate: '06/03/2021',
  dateResult:'Date Result',
  dateResultDate:'09/03/2021',
  Testtype: 'Test type',
  Quicktest: 'Quick test',
  Testresult: 'Test result',
  Testfailed: 'Test failed',
  SymptomsTest: 'Symptoms',
  textInput: 'Yes',
  dateReported: 'Date Reported',
  UrlLogout: 'https://ancient-citadel-41771.herokuapp.com/api/v1/logout',
  urlPlaces: 'https://ancient-citadel-41771.herokuapp.com/places'
};
