export const SymptomsConstants = {
  Symptoms: 'Symptoms',
  Bad: 'BAD',
  Fever: 'Fever',
  homeScreen: 'HomeScreen',
  fever: 'Fever or chills',
  cough: 'Dry Cough',
  shortness: 'Shortness of breath or difficulty breathing',
  save: 'SAVE',
  fatigue: 'Fatigue',
  sorethroat:'Sore throat',
  commonSymptoms:'MOST COMMON SYMPTOMS',
  next: 'Next',
  sense: 'Loss of sense of smell or taste',
  severeSymptoms:'SEVERE SYMPTOMS',
  breathing:'Difficulty breathing or feeling short of breath',
  Chest_pain: 'Chest pain or pressure', 
  move:'Inability to speak or move',
  fingers:'Loss of color in the fingers or toes',
};
